name = "MI BENBO"
author = "Vitafeu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4317a96feee1e1051abb8b1a211a42c0ae86884445f43664b949ac31ad458f1c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
