name = "MI BENBO"
author = "Vitafeu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a8ce1b65d3c5f6bc49cde9a732174691a49eb529c72716886358c4061fe102a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
