name = "MI BENBO"
author = "Vitafeu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83774a9bdada38ad068707a2597b7c2f73a68a87462c081a784906eba7f8ade6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
